[model]
package = "bonito.models.rnn_ctc_crf"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
rnn_type = "lstm"
activation = "swish"
blank_score = 2.0

[global_norm]
state_len = 5

[basecaller]
batchsize = 128
chunksize = 10000
overlap = 500
