[model]
package = "bonito.models.transformer"

[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[qscore]
bias = 0.0
scale = 1.0

[encoder]
stride = 5
winlen = 19
scale = 5.0
features = 768
activation = "swish"
blank_score = 2.0
num_layers = 6
attn_heads = 8
inner_size = 2048
fnn_dropout = 0.1
attn_score_dropout = 0.1
attn_layer_dropout = 0.1
hidden_act = 'relu'
mask_future = false
pre_ln = false
pre_ln_final_layer_norm = true

[global_norm]
state_len = 5

[basecaller]
batchsize = 128
chunksize = 10000
overlap = 500
